export enum TrafficReportDimensionEnum {
  DAY = "DAY",
  LISTING = "LISTING",
}

export enum TrafficReportMetricEnum {
  CLICK_THROUGH_RATE = "CLICK_THROUGH_RATE",
  LISTING_IMPRESSION_SEARCH_RESULTS_PAGE = "LISTING_IMPRESSION_SEARCH_RESULTS_PAGE",
  LISTING_IMPRESSION_STORE = "LISTING_IMPRESSION_STORE",
  LISTING_IMPRESSION_TOTAL = "LISTING_IMPRESSION_TOTAL",
  LISTING_VIEWS_SOURCE_DIRECT = "LISTING_VIEWS_SOURCE_DIRECT",
  LISTING_VIEWS_SOURCE_OFF_EBAY = "LISTING_VIEWS_SOURCE_OFF_EBAY",
  LISTING_VIEWS_SOURCE_OTHER_EBAY = "LISTING_VIEWS_SOURCE_OTHER_EBAY",
  LISTING_VIEWS_SOURCE_SEARCH_RESULTS_PAGE = "LISTING_VIEWS_SOURCE_SEARCH_RESULTS_PAGE",
  LISTING_VIEWS_SOURCE_STORE = "LISTING_VIEWS_SOURCE_STORE",
  LISTING_VIEWS_TOTAL = "LISTING_VIEWS_TOTAL",
  SALES_CONVERSION_RATE = "SALES_CONVERSION_RATE",
  TOTAL_IMPRESSION_TOTAL = "TOTAL_IMPRESSION_TOTAL",
  TRANSACTION = "TRANSACTION",
}
